[package]
name = "range_checker"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
risc0-zkvm-platform = "1.2.0"